services:
  web:
    image: "platita_api_v1"
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000;
      - JWT__KEY=${JWT__KEY}
      - JWT__ISSUER=${JWT__ISSUER}
      - JWT__AUDIENCE=${JWT__AUDIENCE}
      - ConnectionStrings__DefaultConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5000:5000"
      # - "127.0.0.1:5001:5001"
    depends_on:
      - db

  db:
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
